# Generated by Django 3.2.13 on 2022-07-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_product',
            name='background',
            field=models.ImageField(default='01.jpg', upload_to='970x647'),
        ),
        migrations.AddField(
            model_name='team',
            name='background',
            field=models.ImageField(default='01.jpg', upload_to='770x860'),
        ),
    ]
