# Generated by Django 3.2.13 on 2022-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_auto_20220721_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='options',
        ),
        migrations.AddField(
            model_name='subscription',
            name='options1',
            field=models.CharField(default='Basic Features', max_length=40),
        ),
        migrations.AddField(
            model_name='subscription',
            name='options2',
            field=models.CharField(default='Basic Features', max_length=40),
        ),
        migrations.AddField(
            model_name='subscription',
            name='options3',
            field=models.CharField(default='Basic Features', max_length=40),
        ),
    ]
