# Generated by Django 3.2.13 on 2022-08-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0003_auto_20220802_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('content', models.TextField(default='No description')),
                ('number', models.IntegerField()),
                ('mail', models.EmailField(blank=True, max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='latest_product',
            name='background',
            field=models.ImageField(default='01.jpg', upload_to='static\\img\\970x647'),
        ),
        migrations.AlterField(
            model_name='team',
            name='background',
            field=models.ImageField(default='01.jpg', upload_to='static\\img\\770x860'),
        ),
    ]
