# Generated by Django 3.2.13 on 2022-08-02 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0005_alter_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
