# Generated by Django 3.2.13 on 2022-08-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0006_contact_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest_product',
            name='icon',
            field=models.CharField(choices=[('service-icon icon-chemistry', 'Chimestry'), ('service-icon icon-screen-tablet', 'Tablet'), ('service-icon icon-badge', 'Badge'), ('service-icon icon-notebook', 'Notebook'), ('service-icon icon-speedometer', 'Speedometer')], default='service-icon icon-chemistry', max_length=40),
        ),
        migrations.AddField(
            model_name='subscription',
            name='icon',
            field=models.CharField(choices=[('service-icon icon-chemistry', 'Chimestry'), ('service-icon icon-badge', 'Badge'), ('icon-shield', 'Shield')], default='service-icon icon-chemistry', max_length=40),
        ),
    ]
