# Generated by Django 3.2.13 on 2022-08-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0007_auto_20220803_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='icon',
            field=models.CharField(choices=[('service-icon icon-chemistry', 'Chimestry'), ('service-icon icon-screen-tablet', 'Tablet'), ('service-icon icon-badge', 'Badge'), ('service-icon icon-notebook', 'Notebook'), ('service-icon icon-speedometer', 'Speedometer')], default='service-icon icon-chemistry', max_length=40),
        ),
    ]
