# Generated by Django 3.2.13 on 2022-08-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0008_about_us_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latest_product',
            name='icon',
        ),
    ]
